apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: boilerapp-ingress
  namespace: boilerapp
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    
    # Redirect HTTP â†’ HTTPS
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    
    # SSL Certificate
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:242880561312:certificate/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

    # Health check
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
spec:
  rules:
    - host: boilerapp.knowerai.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: boilerapp-service
                port:
                  number: 80
