apiVersion: v1
kind: Service
metadata:
  name: boilerapp-service
  namespace: boilerapp
spec:
  type: LoadBalancer
  selector:
    app: boilerapp
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
